### ISSUE TITLE
Add an option "Other" to licenses

### ISSUE THREAD

**Issue by RibeiroAna** [pytest-dev/cookiecutter-pytest-plugin#20]
Right now there is only three options of license, there should be a new named "other", so the user could type the license that he/she wants

**Comment by hackebrot** [comment]
We could use automatic retrieval from github to fetch more license texts. However this would require a network connection. Not sure if that's something we want for this very minimal template.

What licenses do you feel are missing?

**Comment by RibeiroAna** [comment]
@hackebrot Mozilla Public License, Apache License, etc.

**Comment by hackebrot** [comment]
I've just added the "Mozilla Public License 2.0".

The template now supports the following licenses:
- "MIT"
- "BSD-3"
- "GNU GPL v3.0"
- "Apache Software License 2.0"
- "Mozilla Public License 2.0"

Please feel free to add more! Any questions, please let me know. 🙇 

/cc @davehunt

**Comment by davehunt** [comment]
Thanks for doing that @hackebrot! 👍
