### ISSUE TITLE
.travis.yml doesn't run flake8

### ISSUE THREAD

**Issue by miketheman** [pytest-dev/cookiecutter-pytest-plugin#23]
Having travis (or appveyor) be able to lint my code and any pull requests as part of a contribution is important, and the current templates do not accounts for a flake8 test env.

**Comment by hackebrot** [comment]
Hi @miketheman! 👋 

Which ``.travis.yml`` file are you referring to? The template's or the one of the generated plugin?

**Comment by miketheman** [comment]
👋 
The generated one - specifically https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/7d7bdcda3f73e299e00d79085854e855b2420569/pytest-%7B%7Bcookiecutter.plugin_name%7D%7D/.travis.yml

It appears to use travis' language to infer python version, so it's unclear where a flake8 testenv might be added.

**Comment by hackebrot** [comment]
Hi @miketheman! 👋 

I just updated the travis config file. Can you please have a look?

Thank you for suggesting this. 🙇

**Comment by miketheman** [comment]
Thanks @hackebrot !
