### ISSUE TITLE
Optionally generate a package which uses flit instead of classic setup.py

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/cookiecutter-pytest-plugin#24]
Howdy!

Just passing by to leave this feature suggestion: optionally use [flit](https://flit.readthedocs.io/en/latest/) instead of the classic `setup.py` for package publishing.

I plan to try out `flit` some time soon, and realized this was a valid enhancement request for `cookiecutter-pytest-plugin`. 😉

**Comment by hackebrot** [comment]
Hey @nicoddemus! 👋 

I'm happy to add this as an option if you found it to be a suitable replacement for ``setup.py`` 👍

**Comment by nicoddemus** [comment]
I didn't get a chance of using it myself, but it seems like a great alternative for pure-python projects as is the case with the majority pytest plugins. 😁

**Comment by gyermolenko** [comment]
@nicoddemus flint->flit

**Comment by bluetech** [comment]
#61 switched to pyproject.toml, and has nothing setuptools specific other than the build backend, so there's not a whole lot of reason to use flit I think.
