### ISSUE TITLE
Update plugin project structure

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/cookiecutter-pytest-plugin#38]
I think it makes sense to introduce a `src` directory like here https://github.com/hackebrot/pytest-emoji/tree/master/src/pytest_emoji to allow for plugins that use multiple files and help with package discovery and automated testing.

**Comment by ionelmc** [comment]
I can make a PR for this if you fancy having cookiecutter-pylibrary's setup.py/tox.ini?
