### ISSUE TITLE
Tests do not work

### ISSUE THREAD

**Issue by mcproger** [pytest-dev/cookiecutter-pytest-plugin#44]
After installing and creating the plugin structure, I try to run original tests, that ship with plugin template. But that does not work. 

For example, one of the tests cannot find default `bar` fixture, and I have this error: 

<img width="889" alt="Снимок экрана 2020-01-25 в 23 33 44" src="https://user-images.githubusercontent.com/25745587/73127009-334fcc00-3fcb-11ea-95bf-aec2abd4602c.png">

Also, `testdir.makeini` does not create any params.

I have  pytest version 5.3.4 and python 3.8.0.

**Comment by mcproger** [comment]
Can someone help me pls?

**Comment by nicoddemus** [comment]
Hi @mcproger, can you please point to the repository?

**Comment by mcproger** [comment]
There is no repository, I just make 

```
$ pip install cookiecutter
$ cookiecutter https://github.com/pytest-dev/cookiecutter-pytest-plugin
$ pytest
```
and get an error message. I mean, default tests generated by template do not work.

**Comment by The-Compiler** [comment]
You will need to install your plugin to test it. Either use something like `tox -e py37` to run your tests, or use `pip install -e .` (with a virtualenv) to install it before running your tests.
