### ISSUE TITLE
Tox virtualenv for Python 3 imports Python 2 libs

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/cookiecutter-pytest-plugin#8]
Apparently there are problems with the virtualenvs that tox creates for the template. :confused: It is trying to import ConfigParser from Python 2 in a Python 3 environment…that’s messed up.

**Comment by maiksensi** [comment]
@hackebrot Any change for a stack trace from the log files? They should be located in the `.tox` directory

**Comment by hackebrot** [comment]
Hi @maiksensi, I think you can easily reproduce this by doing the following:

1. ``git clone`` this repo
1. ``pip install tox``
1. ``tox``

**Comment by hackebrot** [comment]
Also the travis build seems to be broken due to this.

https://travis-ci.org/pytest-dev/cookiecutter-pytest-plugin

It is supposed to create a new pytest plugin via **cookiecutter** and run the enclosed tests, which in turn make sure that the fixture and the cli option work.

**Comment by hackebrot** [comment]
I rewrote the tests to use ``tox``. I think we're good. :no_mouth:
